### PR TITLE
Jpr 0 dbraley 2

### PR DESCRIPTION
**Pull request by dbraley**

### CODE REVIEW

**Comment by StevenACoffman** [comment]
Testing

**Comment by StevenACoffman** [comment]
Sorry for the noise. I was testing a minikube jenkins pipeline's ability to authenticate to github.

**Comment by StevenACoffman** [comment]
Awww

**Comment by dbraley** [comment]
lol, sorry. just doing some cleanup. Figured after more than a year and presumably no authorized maintainers, this was probably dead.

**Pull request closed without merging**
